version: '3'
services:
  web:
    image: "webapi:latest"
    ports:
      - "8080:8080"
    environment:
      - DB_MIGRATE=true
      - DB_HOSTNAME=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_DATABASE=webapi
      - DB_CHARSET=utf8mb4
      - DB_COLLATION=utf8mb4_unicode_ci
      - DB_PARAMETER=parseTime=true&allowNativePasswords=true
  db:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes